### ISSUE TITLE
some of the units have the incorrect value for speed, fire rate, damage, or build speed.     (bonus. the trident and ghoul bomber have their weapon offset)

### ISSUE THREAD

**Issue by littlekatter330** [VvSeanGTvV/V5-Classic#2]
this applies to trident, dart,  javelin, lich, glaive, chaos array, ghoul bomber, and all air units that shoot and the ground mechs cant boost.

**Comment by littlekatter330** [comment]
oh and forgot a few things like snek, and scorch     :)

**Comment by VvSeanGTvV** [comment]
I'll try fixing them for the time being I added the snek function, and fixed the trident and ghoul bomber weapons being offset.

**Comment by littlekatter330** [comment]
@VvSeanGTvV i have a question when will the mech pads be done

**Comment by VvSeanGTvV** [comment]
Fortunately the mod is not capable of making a mech pad, and right now I'm making a java mod or i suppose a overhaul changes for this mod. But thanks for asking.

**Comment by littlekatter330** [comment]
make them cores that can be placed any ware but they have a item limit of 1

(they can't be placed on cores)

**Comment by littlekatter330** [comment]
oh and draug miners you need to research the flare fix that
